### PR TITLE
Updated for v0.11.1-beta, now includes all proto services

### PR DESCRIPTION
**Pull request by LNBIG-COM**
Here is fresh, tested by me, lnd-async for LND v0.11.1-beta, now includes all proto services

### CODE REVIEW

**Comment by bmancini55** [comment]
Awesome, looks great. Any interesting in being a project maintainer?

**Comment by LNBIG-COM** [comment]
> Awesome, looks great. Any interesting in being a project maintainer?

Yes, if you don't have a free time for this project I can support it ;-)
I use your module for my scriptrs and project so i will support it for me in any case :)
So you can add me to project mantainers if you want. Thanks!

P.S. I have not been involved in supporting other people's projects yet, so I will need to master this business a little :)

**Comment by bmancini55** [comment]
Awesome, yeah I just realized your last PR sat there for many months!  We use this library but don't always update our LND nodes that frequently.  I'll add you as a maintainer so it's easier for everyone haha, thanks!

**Comment by bmancini55** [comment]
Invite sent and lnd-async@4.1.0 has been published

**Comment by LNBIG-COM** [comment]
> Invite sent and lnd-async@4.1.0 has been published

Thank you very much! I joined ;-)

**Comment by LNBIG-COM** [comment]
> Awesome, looks great. Any interesting in being a project maintainer?

Hi,

You wrote to me about something, and I can't seem to find where, asking if I have a profile on npmjs.com so I can make releases. I created an account ( https://www.npmjs.com/~lnbig ), but I'm currently not seeing the option to add a project to maintain, so I can update the lnd-async release directly on npmjs.
Could you somehow add me there as a maintainer?

Thank you!

**Pull request merged**
